# Generated by Django 4.2 on 2023-05-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_is_cancelled_order_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_orders',
            field=models.ManyToManyField(blank=True, to='api.order'),
        ),
    ]
