# Generated by Django 4.2 on 2023-05-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_delivery_address_alter_profile_my_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
