# Generated by Django 4.2 on 2023-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('house_name', models.CharField(max_length=500)),
                ('street_name', models.CharField(max_length=500)),
                ('state_name', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
