# Generated by Django 4.2 on 2023-05-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_address_house_name_alter_address_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
